### ISSUE TITLE
Label of the recommendation task

### ISSUE THREAD

**Issue by wxl1999** [jfzhouyoo/CR-GIS#1]
Hi, I read your code and find that the label of the recommendation task is the last entity in each triple of the path in metadata.
https://github.com/jfzhouyoo/CR-GIS/blob/a6d48166a0d40d7ddeb5f55b0b07800e58ddbf68/CR-GIS/src/dataset_opendialkg.py#L107
However, in the dataset, some of the last entity in each triple is not the item but the attribute.
I am quite confused about this, can you give an explanation about it?

**Comment by jfzhouyoo** [comment]
We found that NER is difficult to accurately extract the item in the response, so here we simply use the last entity of the KG path parallel to the conversation in OpenDialKG as the recommendation target.

Both attribute and item are presented in the form of entities in the knowledge graph, so we also extend the attribute as the recommendation target.

**Comment by wxl1999** [comment]
Thanks!
